import PwaWarning from "./components/pwa-warning";
import "./app.scss";
import FlexBox from "./components/flex/flexBox";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FlexBox justifyContent="center" style={{ width: "100%" }}>
        <PwaWarning />
      </FlexBox>
      <body>{children}</body>
    </html>
  );
}
